### ISSUE TITLE
Add an extension function `String.toTextRef()`

### ISSUE THREAD

**Issue by juschmitt** [ioki-mobility/TextRef#136]
Should there be an extension function `fun String.toTextRef(): TextRef` to turn a String into TextRef? 

Maybe additionally there could be one for string resources? Not sure tho about that.

What do you think?

**Comment by StefMa** [comment]
What would be the benefit over `TextRef.string("string")`? 🤔 
```kotlin
"StefMa".toTextRef()
TextRef.string("StefMa")
```

**Comment by vlh-ioki** [comment]
I like the idea!

**Comment by juschmitt** [comment]
> What would be the benefit over `TextRef.string("string")`? 🤔
> 
> ```kotlin
> "StefMa".toTextRef()
> TextRef.string("StefMa")
> ```

IMO the main benefit is function chaining. Here is an overly simplified example:
```kotlin
// Say you have this function that returns a String
fun Address.toFormattedAddress(): String { /* ... */ }

usersAddress.toFormattedAddress().toTextRef()
// vs
TextRef.string(usersAddress.toFormattedAddress())

// Or assume you get data out of an api model:
product.productName.toTextRef()
//vs 
TextRef.string(product.productName)
```

**Comment by StefMa** [comment]
Thanks for the feedback!
Really appreciate it.

However I don't think such an extension function should be part of the core library.
It should be separated from the core logic, like we did with the `compose` module.
On the other side, adding a third module (like `extension` to place a single function inside) is a bit overkill.

For now I will not add, but feel free to add it to your own code base if you like 👍.
