### ISSUE TITLE
Support jetpack compose 

### ISSUE THREAD

**Issue by StefMa** [ioki-mobility/TextRef#29]
Add a convenient wrapper around `.resolve(context)`

```
@Composable
fun textRef(textRef: TextRef): String = textRef.resolve(LocalContext.current)

@Composable
fun textRefOrNull(textRef: TextRef?): String? = textRef?.resolve(LocalContext.current)
```

Stuff to think about/find out
- if compose added, how behaves dependents that doesn't use compose
- do we need another artifact for that? (textref-compose)?
- ...

**Comment by StefMa** [comment]
We need to update the Readme.
minSdk is 21
And add compose Infos to it

**Comment by gustav-es** [comment]
I'm super happy to see you putting in work into this! We use it at my current job :)

I know I'm not a co-owner of this lib anymore, but I would seriously reconsider adding a dependency to compose to the lib, as it increases the APK size (debug build, no r8 shrinking) by 3.6 MB and pulls in a ton of unnecessary libraries for people not using compose.

<img width="591" alt="image" src="https://user-images.githubusercontent.com/94970183/236820799-7b29f73b-1e61-4cbf-9020-ca818387dd55.png">

I compared 1.3.1 with current main.

Adding a "support library" like `textref-compose` seems like the right approach IMO.

**Comment by StefMa** [comment]
Hey Gustav 👋,

thanks for the feedback! I really appreciate it.
I thought about this as an option as well. At the end I decided to put it into the core lib as long as it doesn't break anything with existing dependants that doesn't use compose yet, not thinking about an increase of the library size itself. 

I think the approach with an helper artifact make sense 👍
Feel free to contribute if you want ☺.

**Comment by StefMa** [comment]
@gustav-es just wanted to let you know that I'm on it.
See https://github.com/ioki-mobility/TextRef/pull/37

**Comment by gustavkarlsson** [comment]
Haha, me too. If your interested I can push the branch?

**Comment by StefMa** [comment]
Hehe, yeah sure.
Maybe we can combine the best of both worlds ☺. Just create a PR 🙃
